{
  "hash": "ea46e4dc96645d9c603916a8d1e0db2d",
  "result": {
    "engine": "knitr",
    "markdown": "::: {.content-hidden}\n\n\\usepackage{amssymb, amsmath, amsthm, amsfonts, bm, bbm, mathrsfs} %math\n\\usepackage[italic,noendash]{mathastext} % required because of bug with mathastext vs amsmath for bold chars\n\\usepackage{mathtools}\n\n%shortcut commands for bold math\n\\newcommand{\\var}{\\mathrm{Var}}\n\\newcommand{\\cov}{\\mathrm{Cov}}\n\\newcommand{\\corr}{\\mathrm{Corr}}\n\n\\newcommand{\\iid}{\\stackrel{iid}{\\sim}}\n\n\\newcommand{\\bfbeta}{\\boldsymbol{\\beta}}\n\\newcommand{\\bftheta}{\\boldsymbol{\\theta}}\n\\newcommand{\\bLambda}{\\boldsymbol{\\Lambda}}\n\\newcommand{\\beps}{\\boldsymbol{\\varepsilon}}\n\n\\newcommand{\\x}{\\mathbf{x}}\n\\newcommand{\\y}{\\mathbf{y}}\n\n\n:::\n\n# Simulating from a Model {#sec-simdata}\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n\nIn @sec-choice we simulated a *probability*: many draws of $\\varepsilon$ for one fixed choice situation. In this chapter we simulate a *dataset*: one draw of $\\varepsilon$ for each of many choice situations. The code changes less than you might expect --- in both cases we draw unobservables and push them through the behavioral rule $h$ --- but the interpretation changes completely. The draws now play the role of the real-world unobservables themselves, and the output is a set of synthetic observations that look exactly like data you might collect.\n\nWhy manufacture fake data when the world is full of real data? Three reasons, in increasing order of importance for this book:\n\n1. **Simulation is the proof that you understand the model.** A model is a description of a data generating process. If you cannot write the twenty lines of code that generate data from that process, then somewhere in the chain --- the utility specification, the error distribution, the choice rule --- sits an assumption you do not actually understand. The mantra from the opening of this book operationalizes here.\n\n2. **Simulated data come with an answer key.** You chose the true parameters, so you know exactly what an estimator *should* find. With real data you can never distinguish \"my estimator is broken\" from \"the world is surprising.\" With simulated data there is no ambiguity, which makes simulation the ultimate debugging environment for estimation code.[^1]\n\n3. **The whole workflow of this book depends on it.** Every estimator we build --- maximum likelihood in @sec-mnl-mle, simulated likelihood in @sec-mixed-msl, Gibbs samplers in @sec-hb-mnl --- will be validated the same way: simulate data with known parameters, estimate, compare. This *simulate-and-recover* loop is the central discipline of computational statistics, and this chapter builds its first half.\n\n[^1]: The Bayesian workflow literature elevates this practice to a principle: @gelman2020 recommend fake-data checking before fitting any model to real data. The same advice appears, in frequentist dress, throughout @rizzo2019.\n\n## The Anatomy of a Simulation Script\n\nRecall the framework of @sec-choice. A choice model specifies a behavioral rule $y = h(\\x, \\beps)$ and a density $f(\\beps)$. To simulate data from the model is to run the data generating process forward, once per observation. Every simulation script in this book --- no matter how elaborate the model --- has the same six steps:\n\n1. **Set the sizes.** How many decision-makers $N$? (Later: how many choice situations $T$, alternatives $J$?)\n2. **Set the true parameters.** Choose $\\bfbeta$ (and later, covariance matrices, class shares, ...). These are the values we will demand our estimators recover.\n3. **Generate the observables.** Create the attribute values $\\x$ for every choice situation.\n4. **Draw the unobservables.** One draw of $\\beps$ from $f$ per choice situation --- the inverse-transform skills of @sec-draws.\n5. **Compute utilities.** Combine steps 2--4 through the utility function.\n6. **Apply the choice rule.** Record $y = h(\\x, \\beps)$ for every observation.\n\nSteps 3 and 4 both call random number generators but play entirely different roles, and confusing them is a common beginner error. The observables in step 3 are random only because *we* are inventing a dataset; in a real study they would come from your experimental design or your survey. The unobservables in step 4 are random *inside the model*: they are the $\\beps$ of @eq-int_indicator, and their distribution $f$ is part of the model specification. When we later estimate models, step 3's values will be data we condition on, while step 4's values will be gone --- visible only through their fingerprints on the choices.\n\n## Example: Simulating Binary Logit Choices {#sec-sim_binary}\n\nLet's simulate the laptop-offer setting of @sec-binary_logit at scale. Each of $N$ shoppers is shown one configured laptop --- a price drawn from the study's range and either the base 8GB or upgraded 16GB memory --- and decides whether to buy it. The model, assembled from @eq-u_binlogit through @eq-bin_logistic_dist:\n\n$$\nU_n = \\x_n'\\bfbeta + \\varepsilon_n, \\qquad\n\\varepsilon_n \\iid \\textrm{Logistic}, \\qquad\ny_n = I\\left[ U_n > 0 \\right]\n$$ {#eq-binlogit-dgp}\n\nwith $\\x_n = (1, \\texttt{price}_n, \\texttt{ram16}_n)$ and the true parameter vector we fixed in @sec-running_example: $\\bfbeta^\\ast = (1.0, -1.2, 0.6)$. The subscript $n$ now indexes shoppers, $n = 1, \\ldots, N$ --- our notation for decision-makers from here on.\n\nHere is the script, with the six steps labeled:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(30)\n\n## 1. sizes\nN <- 500\n\n## 2. true parameters\nbeta <- c(1.0, -1.2, 0.6)\n\n## 3. observables: one laptop offer per shopper\nprice <- runif(N, min = 0.8, max = 2.4)   # in $1,000s\nram16 <- rbinom(N, size = 1, prob = 0.5)  # memory upgrade?\nX <- cbind(1, price, ram16)               # N x 3 matrix\n\n## 4. unobservables\neps <- rlogis(N)\n\n## 5. utilities\nU <- as.vector(X %*% beta) + eps\n\n## 6. choices\ny <- as.integer(U > 0)\n\nhead(data.frame(y, price, ram16), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  y     price ram16\n1 1 0.9580525     0\n2 0 1.5811709     0\n3 1 1.3824588     1\n4 0 1.4729906     0\n```\n\n\n:::\n:::\n\n\n\n\n\n\nTwenty lines, most of them comments. A few implementation notes deserve attention, because the same patterns recur in every simulator we write:\n\n- **The design matrix `X`.** We assemble the observables into an $N \\times K$ matrix whose columns match the entries of $\\bfbeta$, including a leading column of ones for the intercept. The matrix product `X %*% beta` then computes all $N$ representative utilities $V_n = \\x_n'\\bfbeta$ (the $V$ of @sec-binary_logit, now one per shopper) in one operation. This is our first taste of a theme that @sec-performance develops fully: organizing data as matrices lets R do the arithmetic in compiled code.\n- **`as.vector()`.** Matrix multiplication returns an $N \\times 1$ matrix; coercing to a plain vector avoids surprises when we add the (vector) draws `eps`. Small thing, classic bug.\n- **One draw per shopper.** Compare with @sec-binary_logit, where we took a thousand draws for a *single* $\\x$. Here each shopper gets exactly one $\\varepsilon_n$ --- their own private circumstances on decision day.\n\nHow many shoppers bought?\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.368\n```\n\n\n:::\n:::\n\n\n\n\n\n\nAbout 37% --- reasonable for laptops priced deliberately on the expensive side. This single number is already a sanity check: a purchase share of 0.99 or 0.01 would send us hunting for a misplaced sign or a wildly mis-scaled price before writing another line.\n\n## Example: Simulating Binary Probit Choices\n\nNow the punchline of this pair of examples. The binary *probit* model is identical to the binary logit in every respect except one: the unobservables are standard normal rather than logistic. In the six-step anatomy, only step 4 changes; in the code, only one line:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(31)\neps_p <- rnorm(N)                       # <- the only change\nU_p   <- as.vector(X %*% beta) + eps_p\ny_p   <- as.integer(U_p > 0)\nmean(y_p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.318\n```\n\n\n:::\n:::\n\n\n\n\n\n\nEverything you believe about a statistical model is a specific line of code in its simulator. The choice of error distribution --- the difference between \"logit\" and \"probit,\" between closed-form choice probabilities (@sec-mnl) and integrals requiring simulation (@sec-mnp) --- is the difference between `rlogis(N)` and `rnorm(N)`.[^2]\n\n[^2]: The purchase shares differ between the two runs (0.368 vs 0.318) partly because of the different error distributions and partly because the draws differ. The standard logistic has variance $\\pi^2/3 \\approx 3.29$, while the standard normal has variance 1, so the *same* $\\bfbeta$ implies different signal-to-noise ratios in the two models. This scale mismatch is not a nuisance --- it is a preview of the identification discussion in @sec-mnl: utility scale and error variance are two sides of one coin.\n\nCan you tell the two datasets apart by looking? Here are their purchase rates plotted against price:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbins <- cut(price, breaks = seq(0.8, 2.4, by = 0.2))\nshares <- rbind(\n    data.frame(bin = levels(bins), model = \"logit\",\n               share = tapply(y,   bins, mean)),\n    data.frame(bin = levels(bins), model = \"probit\",\n               share = tapply(y_p, bins, mean))\n)\nggplot(shares, aes(x = bin, y = share, group = model, linetype = model)) +\n    geom_line() + geom_point(size = 1.5) +\n    labs(x = \"price bin ($1,000s)\", y = \"share who bought\", linetype = NULL) +\n    theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![Purchase shares by price bin for one simulated logit dataset and one simulated probit dataset (N = 500 each). The error distribution that separates the two models is essentially invisible in raw data summaries.](03_simdata_files/figure-pdf/fig-logit-probit-compare-1.pdf){#fig-logit-probit-compare fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\nNot really --- both fall with price, with sampling noise dominating any difference in curve shape. Two lessons hide in this modest picture. First, model assumptions about unobservables are *not* readable off raw data; distinguishing logit from probit takes likelihood-based tools (and even then, @sec-mnp will show, the practical differences are subtle). Second, and more optimistically: since the models are so similar, the estimation machinery we build for one will transfer to the other with small changes --- the exact program of Part IV.\n\n## Packaging the Simulator as a Function {#sec-sim-function}\n\nWe will need to simulate binary choice data again --- in @sec-likelihood to feed our first likelihood, in @sec-optimization to test our first optimizer, in @sec-gibbs to check the Albert--Chib sampler. Copy-pasting the script each time invites drift: a tweak here, a forgotten seed there, and soon no two chapters use quite the same data generating process. The remedy is to package the simulator as a function with explicit arguments.\n\nDoing so forces a design decision worth pausing over: *what should be an argument, and what should be internal?* Three reasonable designs:\n\n- **(a) Everything internal.** `sim_binary_data()` with no arguments, returning one canonical dataset. Simple, but useless the moment we want a different $N$ or $\\bfbeta$ --- and we will want both, e.g., to study how estimator precision varies with sample size in @sec-mnl-mle.\n- **(b) Pass the design matrix in.** `sim_binary_data(X, beta)`. Maximally flexible --- the caller controls the covariates entirely --- and the right choice when a real study's design is fixed. But every call now requires boilerplate to build `X`.\n- **(c) Generate covariates internally, parameters as arguments.** The function owns the *study design* (prices uniform on the study range, memory upgrades at random) while the caller controls the *scientific quantities* ($N$, $\\bfbeta$).\n\nWe choose (c), with (b)'s escape hatch: covariates are generated internally by default, but a caller who needs custom covariates can supply their own `X`. This layered design --- sensible defaults, full control available --- costs three lines and is a pattern worth stealing for your own work:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_binary_data <- function(N, beta, X = NULL,\n                            dist = c(\"logistic\", \"normal\")) {\n    dist <- match.arg(dist)\n    if (is.null(X)) {\n        price <- runif(N, min = 0.8, max = 2.4)\n        ram16 <- rbinom(N, size = 1, prob = 0.5)\n        X <- cbind(1, price, ram16)\n    }\n    eps <- switch(dist,\n                  logistic = rlogis(N),\n                  normal   = rnorm(N))\n    U <- as.vector(X %*% beta) + eps\n    data.frame(y = as.integer(U > 0), X[, -1, drop = FALSE])\n}\n\nset.seed(32)\nd <- sim_binary_data(N = 500, beta = c(1.0, -1.2, 0.6))\nhead(d, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  y    price ram16\n1 0 1.609345     1\n2 0 1.751693     1\n3 0 2.093995     0\n```\n\n\n:::\n:::\n\n\n\n\n\n\nNote the `dist` argument: because logit and probit differ by one line, one simulator serves both models, and the difference is now *named* rather than buried. The function returns a plain data frame --- one row per shopper, the choice and the attributes, no intercept column --- because that is the shape of real choice data arriving on your desk. Rebuilding the intercept-bearing `X` matrix from such a data frame is precisely the \"organizing the data\" work of @sec-data.\n\n## Sanity Checks on Simulated Data {#sec-sanity-checks}\n\nYou wrote the simulator, so it is correct... probably. Twenty lines is enough room for a sign error, a swapped argument, or a distribution with the wrong scale, and an error here poisons everything downstream: you cannot debug an estimator against data that misrepresent the model. Before any simulated dataset earns our trust, it faces checks of increasing stringency.\n\n**Level 1: marginal summaries.** The purchase share (0.31 above) should be sane, and each covariate should have the intended distribution. One-liners: `mean(d$y)`, `summary(d$price)`, `table(d$ram16)`.\n\n**Level 2: directional relationships.** Choices should respond to attributes in the direction the parameters dictate --- buy rates falling with price, rising with the memory upgrade:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(d$y, d$ram16, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        0         1 \n0.2339623 0.3957447 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe 16GB laptops sell more often, as $\\beta_{\\texttt{ram16}} = 0.6 > 0$ demands.\n\n**Level 3: quantitative agreement with theory.** The strongest check compares simulated frequencies against the model's *implied probabilities* --- the closed-form curve from @sec-binary_logit. For the binary logit we know $p(y=1|\\x) = e^{\\x'\\bfbeta}/(1+e^{\\x'\\bfbeta})$, so binned empirical purchase rates should scatter around that curve, hugging it more tightly as $N$ grows:\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(33)\nbig <- sim_binary_data(N = 20000, beta = c(1.0, -1.2, 0.6))\nb16 <- big[big$ram16 == 1, ]\n\nbins <- cut(b16$price, breaks = seq(0.8, 2.4, by = 0.1))\nemp  <- data.frame(\n    price = tapply(b16$price, bins, mean),\n    share = tapply(b16$y,     bins, mean)\n)\n\nggplot(emp, aes(x = price, y = share)) +\n    geom_function(fun = function(p) plogis(1.0 - 1.2*p + 0.6),\n                  linewidth = 0.8, color = \"grey40\") +\n    geom_point() +\n    labs(x = \"price ($1,000s)\", y = \"P(buy)\")\n```\n\n::: {.cell-output-display}\n![Level-3 sanity check: empirical purchase shares by price bin (points, 16GB laptops only, N = 20,000) against the model-implied logit curve (line). Agreement of this quality is strong evidence the simulator implements the model it claims to.](03_simdata_files/figure-pdf/fig-sanity-curve-1.pdf){#fig-sanity-curve fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n(We used `plogis()` --- the logistic CDF --- to evaluate the logit formula; after @sec-draws you know exactly what that function is.) The points ride the curve. If they rode a *different* curve --- shifted, flipped, compressed --- the discrepancy's shape would point to the bug: wrong sign, wrong coefficient, wrong error scale.\n\nThese checks may feel excessive for twenty lines of code, but the habit scales. In @sec-mixed-msl the simulator will have random coefficients drawn through a Cholesky factor; in @sec-hb-mnl entire populations of parameters. Simulators grow; the checking discipline is what keeps their complexity honest.\n\n## The Simulate-and-Recover Workflow {#sec-sim-recover}\n\nStep back and look at what we can now do. Given any fully specified choice model, we can manufacture a dataset from it --- and we know the true $\\bfbeta$ behind that dataset. The natural next question defines the rest of Part I: *pretending we don't know $\\bfbeta$, can we get it back from the data alone?*\n\nThat question, asked and answered on repeat, is the **simulate-and-recover workflow**:\n\n1. Choose true parameters $\\bfbeta^\\ast$.\n2. Simulate a dataset from the model at $\\bfbeta^\\ast$ (this chapter).\n3. Feed the dataset --- *not* the parameters --- to an estimation routine (chapters 5--6 build one).\n4. Compare the estimate $\\hat{\\bfbeta}$ to $\\bfbeta^\\ast$.\n\nIf $\\hat{\\bfbeta}$ lands close to $\\bfbeta^\\ast$ --- with \"close\" made precise by the standard errors of @sec-optimization and the replication studies of @sec-mnl-mle --- then model, simulator, and estimator all cohere. When recovery fails, something specific is broken, and the failure pattern usually says what: a sign flip suggests a coding error in the likelihood; estimates biased toward zero suggest an error-scale mismatch; one wild coefficient suggests an identification problem (@sec-mnl). Experienced modelers read recovery failures the way mechanics read engine noises, and the only way to develop that ear is to run the loop many times. We will.\n\nThe loop has one more virtue worth advertising now: it is how you *develop* new models, not just how you learn old ones. When you invent a custom model for your own research --- the destination of @sec-extensions --- the first thing you will build is its simulator, and simulate-and-recover will be the test bench that tells you whether your custom estimator actually works before it ever touches real data.\n\n## Key Learnings\n\n- Simulating data from a model is running the data generating process forward: set sizes, set true parameters, generate observables, draw unobservables, compute utilities, apply the choice rule. Every simulator in this book follows these six steps.\n- The draws now *are* the model's unobservables --- one per choice situation --- unlike @sec-choice's many-draws-per-situation integral approximation. Same generators, different role.\n- Model assumptions live in specific lines of code: logit vs probit is `rlogis(N)` vs `rnorm(N)`, one line apart and nearly indistinguishable in raw data. (And the two models' different error variances previewed the scale-identification issue of @sec-mnl.)\n- Package simulators as functions. Deciding what is an argument ($N$, $\\bfbeta$, optionally `X`) and what is internal (the study design) is a real design choice; we chose defaults-with-escape-hatches, a pattern that recurs in all our reusable code.\n- Never trust an unchecked simulator. Check marginal summaries, directional effects, and --- the gold standard --- quantitative agreement between empirical frequencies and model-implied probabilities (@fig-sanity-curve).\n- The simulate-and-recover workflow --- simulate at known $\\bfbeta^\\ast$, estimate, compare --- is the central discipline of this book. We have built the \"simulate\" half; Part I's remaining chapters build \"recover.\"\n",
    "supporting": [
      "03_simdata_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}