<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Choice Models and Simulation – Discrete Choice Model Estimation with R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/02_draws.html" rel="next">
<link href="../index.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b343bb23504f009ddf7b24643a6af19a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-793f8d10441867c48bd9ff7da57d4687.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01_choice.html">Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/01_choice.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Choice Models and Simulation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Discrete Choice Model Estimation with R</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/dyavorsky/dcme-r" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Discrete-Choice-Model-Estimation-with-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01_choice.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Choice Models and Simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/02_draws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Drawing from Densities</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03_simdata.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulating from a Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Organizing Choice Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05_likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">From Choice Data to Likelihood</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06_optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Numerical Optimization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">The MNL Family, by Likelihood</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07_mnl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">The Multinomial Logit Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08_mnl_mle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estimating the MNL by Maximum Likelihood</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09_performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Code Performance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10_iia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Relaxing IIA: Nested Logit and GEV Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11_latentclass.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">The Latent Class MNL Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12_msl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Maximum Simulated Likelihood</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/13_mixed_msl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Mixed MNL Model by MSL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/14_limits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">The Limits of Likelihood</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">The MNL Family, by Bayes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/15_bayes_mnl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Bayesian Estimation of the MNL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/16_gibbs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Gibbs Sampling and Hierarchical Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/17_hb_mnl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The Hierarchical Bayesian MNL</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Beyond Logit: The Multinomial Probit</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/18_mnp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">The Multinomial Probit Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/19_mnp_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Estimating the MNP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/20_hb_mnp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">The Hierarchical Bayesian MNP</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Using and Extending the Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/21_postestimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Post-Estimation: Inference, WTP, and Market Simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/22_extensions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Extensions: Building Your Own Model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Appendix</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-framework-for-choice" id="toc-a-framework-for-choice" class="nav-link active" data-scroll-target="#a-framework-for-choice"><span class="header-section-number">1.1</span> A Framework for Choice</a></li>
  <li><a href="#sec-simple_example" id="toc-sec-simple_example" class="nav-link" data-scroll-target="#sec-simple_example"><span class="header-section-number">1.2</span> A Simple Example</a></li>
  <li><a href="#sec-binary_logit" id="toc-sec-binary_logit" class="nav-link" data-scroll-target="#sec-binary_logit"><span class="header-section-number">1.3</span> A Binary Logit Example</a>
  <ul class="collapse">
  <li><a href="#a-model-has-implications" id="toc-a-model-has-implications" class="nav-link" data-scroll-target="#a-model-has-implications"><span class="header-section-number">1.3.1</span> A model has implications</a></li>
  </ul></li>
  <li><a href="#sec-running_example" id="toc-sec-running_example" class="nav-link" data-scroll-target="#sec-running_example"><span class="header-section-number">1.4</span> The Running Example: A Laptop Choice Study</a></li>
  <li><a href="#the-road-ahead" id="toc-the-road-ahead" class="nav-link" data-scroll-target="#the-road-ahead"><span class="header-section-number">1.5</span> The Road Ahead</a></li>
  <li><a href="#key-learnings" id="toc-key-learnings" class="nav-link" data-scroll-target="#key-learnings"><span class="header-section-number">1.6</span> Key Learnings</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dyavorsky/dcme-r/edit/main/chapters/01_choice.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/01_choice.html">Foundations</a></li><li class="breadcrumb-item"><a href="../chapters/01_choice.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Choice Models and Simulation</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-choice" class="quarto-section-identifier"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Choice Models and Simulation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>It is instructive to start with the first sentence of <span class="citation" data-cites="train2009">Train (<a href="references.html#ref-train2009" role="doc-biblioref">2009</a>)</span> Section 1.3, “Discrete choice analysis consists of two interrelated tasks: <strong>specification</strong> of the behavioral model and <strong>estimation</strong> of the parameters of that model” (emphasis added). Notably, chapters 1–7 of <span class="citation" data-cites="train2009">Train (<a href="references.html#ref-train2009" role="doc-biblioref">2009</a>)</span> only specify models; there is not even a hint of model estimation. We too begin with a focus on model specification.</p>
<p>Let me be clear: many students will see <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> later in this section and immediately think about “fitting” a model; that is, they assume they have data that they will put into an estimation routine to find estimates of the parameters of the model. We are not there yet! At this early stage in the book, we are only specifying models; that is, listing sets of assumptions about data generating processes and exploring the implications of those assumptions. There are no data yet. There will be parameters introduced in our choice of model specification, but we are not yet estimating those parameters. Have patience, we will eventually do these things.</p>
<section id="a-framework-for-choice" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="a-framework-for-choice"><span class="header-section-number">1.1</span> A Framework for Choice</h2>
<p>Train denotes the outcome in any given choice situation as <span class="math inline">\(y\)</span>, determined by some observable factors collected in the vector <span class="math inline">\(\mathbf{x}\)</span> and some unobservable factors collected in the vector <span class="math inline">\(\boldsymbol{\varepsilon}\)</span>. The factors (<span class="math inline">\(\mathbf{x}\)</span> and <span class="math inline">\(\boldsymbol{\varepsilon}\)</span>) relate to the agent’s choice (<span class="math inline">\(y\)</span>) through a function <span class="math inline">\(y = h(\mathbf{x}, \boldsymbol{\varepsilon})\)</span>. We assume for the moment that we know <span class="math inline">\(h(\cdot)\)</span> and that <span class="math inline">\(\mathbf{x}\)</span> and <span class="math inline">\(\boldsymbol{\varepsilon}\)</span> are length-one vectors (i.e., scalars) denoted <span class="math inline">\(x\)</span> and <span class="math inline">\(\varepsilon\)</span>.</p>
<p>Since we do not observe <span class="math inline">\(\varepsilon\)</span>, we can’t predict <span class="math inline">\(y\)</span> exactly. Instead, we focus on the probability of <span class="math inline">\(y\)</span>, that is:</p>
<p><span id="eq-int_indicator"><span class="math display">\[
\begin{aligned}
p(y|x)
&amp;= \Pr \left( \varepsilon \textrm{ such that } h(x,\varepsilon)=y \right) \\
&amp;= \Pr \left( I \left[ h(x,\varepsilon)=y \right] = 1 \right) \\
&amp;= \int I \left[ h(x,\varepsilon)=y \right] f(\varepsilon) \, d\varepsilon
\end{aligned}
\tag{1.1}\]</span></span></p>
<p>Read the last line slowly, because the rest of this book lives inside it. The indicator function <span class="math inline">\(I[\cdot]\)</span> equals 1 when the unobserved factors produce the outcome <span class="math inline">\(y\)</span> and equals 0 otherwise. The integral averages that indicator over all the values the unobserved factors might take, weighting by their density <span class="math inline">\(f(\varepsilon)\)</span>. In words: <em>the probability of an outcome is the share of the unobserved-factor distribution that produces that outcome.</em> Every choice probability we compute in this book — logit, probit, nested, mixed, hierarchical — is an instance of <a href="#eq-int_indicator" class="quarto-xref">Equation&nbsp;<span>1.1</span></a> with a particular choice of <span class="math inline">\(h\)</span> and <span class="math inline">\(f\)</span>.</p>
<p>For certain special choices of <span class="math inline">\(h\)</span> and <span class="math inline">\(f\)</span>, a closed-form expression<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> for the integral is available. But more generally, for almost any choice of <span class="math inline">\(h\)</span> and <span class="math inline">\(f\)</span>, we can approximate the integral through simulation. Train provides pseudo code on how to do so:</p>
<ol type="1">
<li>Repeat the following two steps many (<span class="math inline">\(r=1, \ldots, R\)</span>) times:
<ul>
<li>Draw <span class="math inline">\(\varepsilon^{(r)}\)</span> from <span class="math inline">\(f(\varepsilon)\)</span>.</li>
<li>Determine whether <span class="math inline">\(h(x,\varepsilon^{(r)}) = y\)</span>. If so, set <span class="math inline">\(I^{(r)}=1\)</span>; else set <span class="math inline">\(I^{(r)}=0\)</span>.</li>
</ul></li>
<li>Average the <span class="math inline">\(R\)</span> values of <span class="math inline">\(I\)</span></li>
</ol>
<p>This procedure is called <em>Monte Carlo integration</em>, and it works because of the Law of Large Numbers: the average of many independent realizations of a random quantity converges to its expectation, and <a href="#eq-int_indicator" class="quarto-xref">Equation&nbsp;<span>1.1</span></a> is exactly an expectation — the expectation of the indicator <span class="math inline">\(I[h(x,\varepsilon)=y]\)</span> taken over <span class="math inline">\(\varepsilon\)</span>. We will lean on this idea repeatedly: in <a href="12_msl.html" class="quarto-xref"><span>Chapter 12</span></a> it will sit <em>inside</em> a likelihood function, and in <a href="15_bayes_mnl.html" class="quarto-xref"><span>Chapter 15</span></a> the same “average over draws” logic will summarize posterior distributions.</p>
<p>Next we look at two examples where we use this procedure to approximate the <span class="math inline">\(p(y|x)\)</span> integral. The first example I made up, and it is deliberately abstract — no economics, just mechanics. The second example is the binary logit model discussed by Train, which we will dress in the story that carries through the entire book: a shopper deciding whether to buy a laptop.</p>
</section>
<section id="sec-simple_example" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="sec-simple_example"><span class="header-section-number">1.2</span> A Simple Example</h2>
<p>Let’s first set up a toy example to demonstrate how simulation can approximate the <span class="math inline">\(p(y|x)\)</span> integral. Suppose <span class="math inline">\(x=0.5\)</span> and <span class="math inline">\(\varepsilon\)</span> is uniformly distributed between <span class="math inline">\(-1\)</span> and <span class="math inline">\(1\)</span>. Define <span class="math inline">\(h(x, \varepsilon)\)</span> to be:</p>
<p><span id="eq-h_uniform"><span class="math display">\[
h(x, \varepsilon) =
    \begin{cases}
        0  &amp; \text{if } x + \varepsilon &lt; 0 \\
        1  &amp; \text{if } x + \varepsilon \in [0,1] \\
        2  &amp; \text{if } x + \varepsilon &gt; 1
    \end{cases}
\tag{1.2}\]</span></span></p>
<p>We’ll focus on the outcome <span class="math inline">\(y=2\)</span>. You can probably intuit that the <span class="math inline">\(p(y=2 | x) = 0.25\)</span> since only one quarter of the time will <span class="math inline">\(\varepsilon\)</span> be sufficiently positive to make <span class="math inline">\(x + \varepsilon &gt; 1\)</span>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Nevertheless, let’s approximate the integral representation of <span class="math inline">\(p(y=2|x)\)</span> through simulation to ensure we understand the process.</p>
<p>To walk you through the code, we first set a seed so that the pseudo-random numbers generated by <code>runif()</code> can be replicated exactly each time the code is run (even on different computers). We then specify that we will use 1,000 draws in the simulation and we create a vector <code>I</code> to hold our results. The simulation occurs via a <code>for()</code> loop where each time through the loop we take a draw of <span class="math inline">\(\varepsilon\)</span>, calculate <span class="math inline">\(0.5 + \varepsilon\)</span> and check whether that sum is greater than one. If so, then <span class="math inline">\(h(x,\varepsilon)=2\)</span> matching the value of <span class="math inline">\(y\)</span> for the choice probability we want to assess — i.e., <span class="math inline">\(p(y=2|x)\)</span> — and thus we store a <span class="math inline">\(1\)</span> in the <span class="math inline">\(r^\textrm{th}\)</span> position of <code>I</code>; otherwise we store a 0. We then average the values in <code>I</code> to get our approximation of <span class="math inline">\(p(y=2|x)\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>I <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">length=</span>R)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(r <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>R) {</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    eps  <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="at">min=</span><span class="sc">-</span><span class="dv">1</span>, <span class="at">max=</span><span class="dv">1</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    h    <span class="ot">&lt;-</span> <span class="fl">0.5</span> <span class="sc">+</span> eps</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    I[r] <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(h <span class="sc">&gt;</span> <span class="dv">1</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(I)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.258</code></pre>
</div>
</div>
<p>The simulated value 0.258 approximates the exact value 0.25 and can be made closer by increasing the number of draws used in the simulation.</p>
<p>Notice that we took draws of <span class="math inline">\(\varepsilon\)</span> to empirically approximate the integral of <span class="math inline">\(p(y|x)\)</span>, but we should not think of these draws as “data” in the sense of a dataset. They are ancillary numbers generated from the distribution of <span class="math inline">\(\varepsilon\)</span> that we use to approximate the integral.</p>
<p>R users will recognize that we can shorten the code by taking advantage of R’s vectorized functions and its conversion of boolean values to 0/1 when used in mathematical operations. Here is a shorter implementation of the simulation; whether it’s “better” code is a matter of preference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( <span class="fu">runif</span>(R, <span class="at">min=</span><span class="sc">-</span><span class="dv">1</span>, <span class="at">max=</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">&gt;</span> <span class="dv">1</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.258</code></pre>
</div>
</div>
<p>That’s it. If you can generate pseudo-random draws from the density <span class="math inline">\(f\)</span> and you know <span class="math inline">\(h\)</span>, approximating a choice probability by simulation might only require a handful of lines of code.</p>
<p>How good is the approximation? Since each <span class="math inline">\(I^{(r)}\)</span> is a Bernoulli random variable with success probability <span class="math inline">\(p = 0.25\)</span>, the simulation average has standard error <span class="math inline">\(\sqrt{p(1-p)/R}\)</span>, which for <span class="math inline">\(R=1{,}000\)</span> is about 0.014. Quadrupling the number of draws halves the standard error — the familiar (and, when you are impatient, infuriating) square-root rate of Monte Carlo methods. We will return to the accuracy of simulated probabilities with much more care in <a href="12_msl.html" class="quarto-xref"><span>Chapter 12</span></a>, where it directly affects the quality of our parameter estimates.</p>
</section>
<section id="sec-binary_logit" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="sec-binary_logit"><span class="header-section-number">1.3</span> A Binary Logit Example</h2>
<p>The toy example had no behavioral content: <span class="math inline">\(h\)</span> was an arbitrary rule. Discrete choice models earn the name <em>behavioral</em> by deriving <span class="math inline">\(h\)</span> from a model of decision-making. The standard construction — which we will use, in increasingly elaborate forms, for the rest of the book — is the <em>random utility model</em>: the decision-maker assigns a utility to each available action and picks the action with the highest utility.</p>
<p>Here is the story we will grow throughout this book. A shopper is considering a laptop. The laptop has observable attributes — its price, its memory, its screen size, its brand — and the shopper has some overall assessment of how much they’d like to own it, which also depends on many things we will never observe: their mood, their current machine’s death rattle, a looming deadline. We collect the observable attributes in a vector <span class="math inline">\(\mathbf{x}\)</span> and bundle everything unobservable into a scalar <span class="math inline">\(\varepsilon\)</span>.</p>
<p>The “binary” part of the model’s name refers to the aspect of the model whereby the decision maker does one of two things; they either take an action (<span class="math inline">\(y=1\)</span>, buy the laptop) or not (<span class="math inline">\(y=0\)</span>, walk away). To tie this model into a framework of behavior, we start with a utility function <span class="math inline">\(U\)</span> for the action:</p>
<p><span id="eq-u_binlogit"><span class="math display">\[
U(\mathbf{x}, \boldsymbol{\beta}, \varepsilon) = \mathbf{x}'\boldsymbol{\beta}+ \varepsilon
\tag{1.3}\]</span></span></p>
<p>where <span class="math inline">\(\mathbf{x}\)</span> is a vector of observable explanatory variables, <span class="math inline">\(\boldsymbol{\beta}\)</span> is a vector of parameters that through the functional form <span class="math inline">\(\mathbf{x}'\boldsymbol{\beta}\)</span> effectively serve as weights on the attributes, and <span class="math inline">\(\varepsilon\)</span> is a scalar collecting the value of everything relevant to the shopper but unobserved by the researcher. The utility of <em>not</em> buying is normalized to zero — a harmless-seeming convention that we will scrutinize carefully in <a href="07_mnl.html" class="quarto-xref"><span>Chapter 7</span></a> (identification) and again in <a href="22_extensions.html" class="quarto-xref"><span>Chapter 22</span></a> (the outside option).</p>
<p>The piece the researcher can compute, <span class="math inline">\(\mathbf{x}'\boldsymbol{\beta}\)</span>, is called the <em>representative utility</em> and gets its own letter, <span class="math inline">\(V\)</span>; the model says total utility is representative utility plus noise, <span class="math inline">\(U = V + \varepsilon\)</span>. The split matters: <span class="math inline">\(V\)</span> is where the parameters live, and <span class="math inline">\(\varepsilon\)</span> is what the integral in <a href="#eq-int_indicator" class="quarto-xref">Equation&nbsp;<span>1.1</span></a> averages over.</p>
<p>Notice that <span class="math inline">\(h\)</span> has grown an argument: once we specify utility, the parameters <span class="math inline">\(\boldsymbol{\beta}\)</span> enter the behavioral rule, so we write <span class="math inline">\(h(\mathbf{x}, \boldsymbol{\beta}, \varepsilon)\)</span> and condition the choice probability on <span class="math inline">\(\boldsymbol{\beta}\)</span> as well — <span class="math inline">\(p(y|\mathbf{x},\boldsymbol{\beta})\)</span>. The framework of <a href="#eq-int_indicator" class="quarto-xref">Equation&nbsp;<span>1.1</span></a> is unchanged; <span class="math inline">\(\boldsymbol{\beta}\)</span> simply rides along with <span class="math inline">\(\mathbf{x}\)</span>. The shopper buys when buying is better than not buying, so the behavioral rule <span class="math inline">\(h\)</span> is:</p>
<p><span id="eq-h_binlogit"><span class="math display">\[
h(\mathbf{x}, \boldsymbol{\beta}, \varepsilon) =
    \begin{cases}
        0  &amp; \text{if} \hspace{1ex} U(\mathbf{x}, \boldsymbol{\beta}, \varepsilon) \le 0 \\
        1  &amp; \text{if} \hspace{1ex} U(\mathbf{x}, \boldsymbol{\beta}, \varepsilon) &gt; 0
    \end{cases}
\tag{1.4}\]</span></span></p>
<p>The “logit” part of the model’s name refers to the choice of <span class="math inline">\(f\)</span>. The binary logit model assumes <span class="math inline">\(\varepsilon\)</span> follows the standard logistic distribution:</p>
<p><span id="eq-bin_logistic_dist"><span class="math display">\[
f(\varepsilon) = \frac{e^{-\varepsilon}}{(1+e^{-\varepsilon})^2}
\tag{1.5}\]</span></span></p>
<p>This particular pairing of <span class="math inline">\(h\)</span> and <span class="math inline">\(f\)</span> is one of the special cases where the integral in <a href="#eq-int_indicator" class="quarto-xref">Equation&nbsp;<span>1.1</span></a> has a closed form. Let me show you why. Integrating <a href="#eq-bin_logistic_dist" class="quarto-xref">Equation&nbsp;<span>1.5</span></a> gives the logistic CDF, <span class="math inline">\(F(\varepsilon) = 1/(1+e^{-\varepsilon})\)</span> (differentiate it to confirm you get <span class="math inline">\(f\)</span> back). The shopper buys when <span class="math inline">\(\mathbf{x}'\boldsymbol{\beta}+ \varepsilon &gt; 0\)</span>, i.e., when <span class="math inline">\(\varepsilon &gt; -\mathbf{x}'\boldsymbol{\beta}\)</span>, so <span class="math display">\[
p(y=1|\mathbf{x},\boldsymbol{\beta}) = \Pr(\varepsilon &gt; -\mathbf{x}'\boldsymbol{\beta}) = 1 - F(-\mathbf{x}'\boldsymbol{\beta}) = 1 - \frac{1}{1+e^{\mathbf{x}'\boldsymbol{\beta}}} = \frac{e^{\mathbf{x}'\boldsymbol{\beta}}}{1+e^{\mathbf{x}'\boldsymbol{\beta}}}
\]</span> No indicator, no integral sign left standing — that is what “closed form” buys us:</p>
<p><span id="eq-binlogit_prob"><span class="math display">\[
p(y=1 | \mathbf{x}, \boldsymbol{\beta}) = \frac{e^{\mathbf{x}'\boldsymbol{\beta}}}{1 + e^{\mathbf{x}'\boldsymbol{\beta}}}
\tag{1.6}\]</span></span></p>
<p>Let’s make it concrete. Suppose the laptop on offer costs $1,500 and has 16GB of RAM (an upgrade over a base 8GB configuration). We describe it with the vector <span class="math inline">\(\mathbf{x}= (1, 1.5, 1)\)</span>: a constant, the price in thousands of dollars, and an indicator for the 16GB memory upgrade. And suppose the weights are <span class="math inline">\(\boldsymbol{\beta}^\ast = (1.0, -1.2, 0.6)\)</span> — the asterisk is our standing notation for <em>true</em> parameter values, the ones the data generating process actually uses, as distinct from candidate values <span class="math inline">\(\boldsymbol{\beta}\)</span> we will later evaluate and estimates <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> we will later compute. The three values: a baseline pull toward buying, a distaste for price, and a taste for memory.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Then</p>
<p><span class="math display">\[
\mathbf{x}'\boldsymbol{\beta}= (1)(1.0) + (1.5)(-1.2) + (1)(0.6) = -0.2
\]</span></p>
<p>and the closed-form probability of purchase is</p>
<p><span id="eq-binlogit_example"><span class="math display">\[
p(y=1 | \mathbf{x}, \boldsymbol{\beta}) = \frac{e^{-0.2}}{1+e^{-0.2}} = 0.45
\tag{1.7}\]</span></span></p>
<p>Even though we have the closed form, let’s approximate the integral by simulation exactly as before, both to practice the procedure and to verify the closed form is what it claims to be. We use <code>rlogis()</code> to take <span class="math inline">\(R=1{,}000\)</span> draws from the standard logistic distribution, and we approximate the integral with the proportion of times <span class="math inline">\(\mathbf{x}'\boldsymbol{\beta}+ \varepsilon\)</span> exceeds the threshold for action (<span class="math inline">\(0\)</span>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2345</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>x    <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">1.5</span>, <span class="dv">1</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">1.0</span>, <span class="sc">-</span><span class="fl">1.2</span>, <span class="fl">0.6</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>U <span class="ot">&lt;-</span> <span class="fu">as.vector</span>(x <span class="sc">%*%</span> beta) <span class="sc">+</span> <span class="fu">rlogis</span>(R)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(U <span class="sc">&gt;</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.434</code></pre>
</div>
</div>
<p>Our simulated value 0.434 approximates the exact value 0.45. The two routes — analytic formula and simulation — agree, as they must. Hold onto this dual view. When a closed form exists we will use it (it is faster and exact), but the simulation route never stops being available, and for most of the models in the second half of this book it is the <em>only</em> route.</p>
<section id="a-model-has-implications" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="a-model-has-implications"><span class="header-section-number">1.3.1</span> A model has implications</h3>
<p>A specified model is a machine for answering “what if” questions, even before any data exist. What does our model say happens to the purchase probability as price varies? We can trace the whole curve by evaluating <a href="#eq-binlogit_prob" class="quarto-xref">Equation&nbsp;<span>1.6</span></a> over a grid of prices, for both memory configurations:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>price <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">0.8</span>, <span class="at">to =</span> <span class="fl">2.4</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>p_buy <span class="ot">&lt;-</span> <span class="cf">function</span>(price, ram16) {</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    v <span class="ot">&lt;-</span> <span class="fl">1.0</span> <span class="sc">-</span> <span class="fl">1.2</span><span class="sc">*</span>price <span class="sc">+</span> <span class="fl">0.6</span><span class="sc">*</span>ram16</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">exp</span>(v) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(v))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>curves <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">price =</span> <span class="fu">rep</span>(price, <span class="at">times =</span> <span class="dv">2</span>),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">ram   =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"8GB"</span>, <span class="st">"16GB"</span>), <span class="at">each =</span> <span class="fu">length</span>(price)),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob  =</span> <span class="fu">c</span>(<span class="fu">p_buy</span>(price, <span class="at">ram16 =</span> <span class="dv">0</span>), <span class="fu">p_buy</span>(price, <span class="at">ram16 =</span> <span class="dv">1</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(curves, <span class="fu">aes</span>(<span class="at">x =</span> price, <span class="at">y =</span> prob, <span class="at">linetype =</span> ram)) <span class="sc">+</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">annotate</span>(<span class="st">"point"</span>, <span class="at">x =</span> <span class="fl">1.5</span>, <span class="at">y =</span> <span class="fu">p_buy</span>(<span class="fl">1.5</span>, <span class="dv">1</span>), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Price ($1,000s)"</span>, <span class="at">y =</span> <span class="st">"P(buy)"</span>, <span class="at">linetype =</span> <span class="st">"Memory"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-price-curve" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-price-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="01_choice_files/figure-html/fig-price-curve-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-price-curve-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: Purchase probability implied by the binary logit model as price varies, for the base (8GB) and upgraded (16GB) memory configurations. The point marks the worked example: a $1,500 laptop with 16GB of RAM.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Two things are worth noticing. First, the curves are S-shaped, not straight lines: the model builds in diminishing sensitivity at the extremes, where the shopper is nearly certain to buy or nearly certain to walk away. Second, the vertical gap between the curves is the effect of the memory upgrade, and it is <em>not constant</em> — it is largest where the purchase decision hangs in the balance. Both properties came free with the logit specification. Whether they are <em>right</em> is an empirical question we are not yet equipped to ask; the point for now is that writing down <span class="math inline">\(h\)</span> and <span class="math inline">\(f\)</span> commits you to implications like these, and you should know what you are committing to.</p>
</section>
</section>
<section id="sec-running_example" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="sec-running_example"><span class="header-section-number">1.4</span> The Running Example: A Laptop Choice Study</h2>
<p>The laptop shopper of the previous section is the seed of the example that grows throughout this book. Since the later chapters build on it, let me lay out the full setting now.</p>
<p>Imagine we field a <em>choice-based conjoint</em> study: we recruit a sample of prospective laptop buyers, and we show each respondent a sequence of choice tasks. In each task, the respondent sees a small set of hypothetical laptops, described by their attributes, and indicates which one they would buy. The attributes and their levels:</p>
<div id="tbl-laptop-attributes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-laptop-attributes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.1: Attributes of the laptop choice study.
</figcaption>
<div aria-describedby="tbl-laptop-attributes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Attribute</th>
<th>Levels</th>
<th>Coding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Brand</td>
<td>Acer, Dell, Apple</td>
<td>dummies <code>dell</code>, <code>apple</code> (Acer is the reference)</td>
</tr>
<tr class="even">
<td>Memory</td>
<td>8, 16, 32 GB</td>
<td>dummies <code>ram16</code>, <code>ram32</code> (8GB is the reference)</td>
</tr>
<tr class="odd">
<td>Screen</td>
<td>13”, 15”</td>
<td>dummy <code>screen15</code> (13” is the reference)</td>
</tr>
<tr class="even">
<td>Price</td>
<td>$800 – $2,400</td>
<td>continuous, in $1,000s</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>This design is modest but honest: it mirrors the structure of real conjoint studies used throughout marketing practice <span class="citation" data-cites="eggers2022">Rao (<a href="references.html#ref-rao2014" role="doc-biblioref">2014</a>)</span>. And it contains, in miniature, everything the models of this book need to exercise: a price for willingness-to-pay questions, brands for intercept-like effects (and, since Apple implies macOS while Dell and Acer imply Windows, a natural <em>nesting</em> of alternatives for <a href="10_iia.html" class="quarto-xref"><span>Chapter 10</span></a>), and attributes over which different respondents plausibly hold different tastes (the heterogeneity that drives everything from <a href="11_latentclass.html" class="quarto-xref"><span>Chapter 11</span></a> onward).</p>
<p>Because we will <em>simulate</em> this study rather than field it, we will always know the true preference parameters, and every estimation method we build will be judged by one standard: does it recover them? The binary examples of the next five chapters strip the setting down to a single laptop offer — buy or don’t — carrying the true parameters <span class="math inline">\(\boldsymbol{\beta}^\ast = (1.0, -1.2, 0.6)\)</span> from <a href="#sec-binary_logit" class="quarto-xref"><span>Section 1.3</span></a>. In <a href="07_mnl.html" class="quarto-xref"><span>Chapter 7</span></a> the full study arrives: <span class="math inline">\(N=500\)</span> respondents, <span class="math inline">\(T=8\)</span> tasks each, <span class="math inline">\(J=3\)</span> laptops per task, and the complete attribute list of <a href="#tbl-laptop-attributes" class="quarto-xref">Table&nbsp;<span>1.1</span></a>.</p>
<p>One warning as the example grows: it is <em>simulated</em>. Simulated data are the right tool for learning estimation — the truth is known, so mistakes are visible — but they are silent about the field problems of real conjoint studies (respondent attention, attribute framing, incentive alignment). When you graduate to real data, pair what you learn here with a treatment of those issues <span class="citation" data-cites="benakiva2019 eggers2022">(e.g., <a href="references.html#ref-benakiva2019" role="doc-biblioref">Ben-Akiva, McFadden, and Train 2019</a>; <a href="references.html#ref-eggers2022" role="doc-biblioref">Eggers et al. 2022</a>)</span>.</p>
</section>
<section id="the-road-ahead" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="the-road-ahead"><span class="header-section-number">1.5</span> The Road Ahead</h2>
<p>You now have the two ideas that generate this entire book:</p>
<ol type="1">
<li><strong>A discrete choice model is a pair <span class="math inline">\((h, f)\)</span></strong> — a behavioral rule and a distribution for what we don’t observe — and the choice probability is the integral in <a href="#eq-int_indicator" class="quarto-xref">Equation&nbsp;<span>1.1</span></a>.</li>
<li><strong>Integrals can be simulated.</strong> Draws from <span class="math inline">\(f\)</span> plus the rule <span class="math inline">\(h\)</span> approximate any choice probability, whether or not a closed form exists.</li>
</ol>
<p>What we cannot yet do is the <em>reverse</em> inference. In this chapter we knew <span class="math inline">\(\boldsymbol{\beta}\)</span> and computed choice probabilities; research runs the other way, from observed choices back to unknown parameters. Getting there requires machinery: drawing from all the densities we’ll need (<a href="02_draws.html" class="quarto-xref"><span>Chapter 2</span></a>), simulating entire datasets rather than single probabilities (<a href="03_simdata.html" class="quarto-xref"><span>Chapter 3</span></a>), organizing choice data so a computer can use them (<a href="04_data.html" class="quarto-xref"><span>Chapter 4</span></a>), turning data plus model into a likelihood (<a href="05_likelihood.html" class="quarto-xref"><span>Chapter 5</span></a>), and maximizing that likelihood numerically (<a href="06_optimization.html" class="quarto-xref"><span>Chapter 6</span></a>). That is Part I, and it is deliberately front-loaded: every hour spent there pays compound interest across Parts II through V.</p>
</section>
<section id="key-learnings" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="key-learnings"><span class="header-section-number">1.6</span> Key Learnings</h2>
<ul>
<li>A discrete choice model is specified by a behavioral function <span class="math inline">\(y = h(\mathbf{x}, \boldsymbol{\varepsilon})\)</span> and a density <span class="math inline">\(f(\boldsymbol{\varepsilon})\)</span> for the unobserved factors. Specification and estimation are distinct tasks, and everything in this chapter was specification.</li>
<li>Our focus is on the <em>probability</em> of a choice outcome, <span class="math inline">\(p(y|\mathbf{x})\)</span>, which is an integral: the share of the unobserved-factor distribution that produces the outcome (<a href="#eq-int_indicator" class="quarto-xref">Equation&nbsp;<span>1.1</span></a>).</li>
<li>That integral has a closed form only for special <span class="math inline">\((h, f)\)</span> pairs — the binary logit is one — but it can be approximated by simulation for almost <em>any</em> pair: draw <span class="math inline">\(\boldsymbol{\varepsilon}\)</span> from <span class="math inline">\(f\)</span>, apply <span class="math inline">\(h\)</span>, average the indicator. Monte Carlo error shrinks at the <span class="math inline">\(\sqrt{R}\)</span> rate.</li>
<li>A fully specified model has testable implications (S-curves, interaction-like gaps) before any data exist. Know what your specification commits you to.</li>
<li>The running example is set: a laptop choice study with known true parameters, <span class="math inline">\(\boldsymbol{\beta}^\ast = (1.0, -1.2, 0.6)\)</span> in its binary form. The rest of the book is about recovering numbers like these from data.</li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-benakiva2019" class="csl-entry" role="listitem">
Ben-Akiva, Moshe, Daniel McFadden, and Kenneth Train. 2019. <em>Foundations of Stated Preference Elicitation: Consumer Behavior and Choice-Based Conjoint Analysis</em>. Vol. 10. Foundations and Trends in Econometrics 1–2. Now Publishers.
</div>
<div id="ref-eggers2022" class="csl-entry" role="listitem">
Eggers, Felix, Henrik Sattler, Thorsten Teichert, and Franziska Völckner. 2022. <span>“Choice-Based Conjoint Analysis.”</span> In <em>Handbook of Market Research</em>, edited by Christian Homburg, Martin Klarmann, and Arnd Vomberg, 781–819. Springer.
</div>
<div id="ref-rao2014" class="csl-entry" role="listitem">
Rao, Vithala R. 2014. <em>Applied Conjoint Analysis</em>. Springer.
</div>
<div id="ref-train2009" class="csl-entry" role="listitem">
Train, Kenneth E. 2009. <em>Discrete Choice Methods with Simulation</em>. 2nd ed. Cambridge University Press. <a href="https://eml.berkeley.edu/books/choice2.html">https://eml.berkeley.edu/books/choice2.html</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>In this context, a <em>closed-form expression</em> means a way of writing the integral so that the anti-derivative sign is not part of solution. For example, the integral <span class="math inline">\(\int x \, dx\)</span> has the closed form expression <span class="math inline">\(x^2/2\)</span> plus some constant. We will see later that the Extreme Value distribution is often chosen for <span class="math inline">\(f\)</span> predominantly because it leads to a closed form expression for the choice probability <span class="math inline">\(p(y|x)\)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>More precisely, <span class="math inline">\(p(y=2|x) = \Pr(x+\varepsilon &gt; 1|x=0.5) = \Pr(\varepsilon &gt; 0.5) = \int_{0.5}^1 f(\varepsilon) d\varepsilon = (0.5\varepsilon)\vert_{0.5}^1 = 0.25\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Only at this early stage — exploring a fully specified model — do we pick values for <span class="math inline">\(\boldsymbol{\beta}\)</span>. In real research, <span class="math inline">\(\mathbf{x}\)</span> is data you collect and <span class="math inline">\(\boldsymbol{\beta}\)</span> contains parameters whose values you estimate. These particular values are not arbitrary: they are the <em>true parameters</em> of the running example, and we will spend most of this book trying to recover them from simulated data. Keep an eye on <span class="math inline">\(-1.2\)</span>, the price coefficient; you will see it many times.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("dcme-r\.danyavorsky\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../index.html" class="pagination-link" aria-label="Welcome">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Welcome</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/02_draws.html" class="pagination-link" aria-label="Drawing from Densities">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Drawing from Densities</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dyavorsky/dcme-r/edit/main/chapters/01_choice.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>